site_name: OOP Practice Docs
pages:
    - Home: index.md
    - Seminars C++:
        - 'Seminar 1': seminar1.md
        - 'Seminar 2': seminar2.md
        - 'Seminar 3': seminar3.md
        - 'Seminar 5': seminar5.md
        - 'Seminar 6': seminar6.md
        - 'Seminar 11': seminar11.md
        - 'Seminar 14': seminar14.md
    - Extras:
        - 'Acceptance': assembla.md
        - 'Using namespaces': using-namespaces.md
        - 'CMake': cmake.md
        - 'Svn': using-subversion.md
        - 'GoogleTest': using-googletest.md
    - Acceptance:
        - "Java": java-acceptance.md
        - "Java Test 1": java-test1.md
        - Java Task1:
            - "Ospanov": java_task1/ospanov.md
        - Java Task2:
            - "Amikishieva": java_task2_results/amikishieva_task2.md
            - "Kambalina": java_task2_results/kambalina_task2.md
            - "Matveev": java_task2_results/matveev_task2.md
            - "Shachenko": java_task2_results/shachenko_task2.md
            - "Dudaev": java_task2_results/dudaev_task2.md
            - "Ospanov": java_task2_results/ospanov.md
            - "Malafeev": java_task2_results/malafeev_task2.md
        - Java Task3:
            - "Amikishieva": java_task3/amikishieva.md
            - "Katchik": java_task3/katchik.md
            - "Svischev": java_task3/svischev.md
            - "Shachenko": java_task3/shachenko.md
            - "Dudaev": java_task3/dudaev.md
            - "Malafeev": java_task3/malafeev.md
        - Java Task4:
            - "Matveev": java_task4/matveev.md
            - "Shachenko": java_task4/shachenko.md
        - Java Task5:
            - "Matveev": java_task5/matveev.md
        - "C++": tasks-acceptance.md
        - C++ Task1:
            - "Amikishieva": task1_test_results/amikishieva_task1_test_results.md
            - "Demidov": task1_test_results/demidov_task1_test_results.md
            - "Dudaev": task1_test_results/dudaev_task1_test_results.md
            - "Kambalina": task1_test_results/kambalina_task1_test_results.md
            - "Shachenko": task1_test_results/shachenko_task1_test_results.md
        - 'Final C++ tasks': final-tasks.md
