site_name: OOP Practice Docs
pages:
    - Home: index.md
    - Seminars C++:
        - 'Seminar 1': 2016.cpp/seminar1.md
        - 'Seminar 3': 2016.cpp/seminar3.md
        - 'Seminar 4': 2016.cpp/seminar4.md
        - 'Archive 2015':
            - 'Seminar 1': cpp/seminar1.2015.md
            - 'Seminar 2': cpp/seminar2.2015.md
            - 'Seminar 3': cpp/seminar3.2015.md
            - 'Seminar 5': cpp/seminar5.2015.md
            - 'Seminar 6': cpp/seminar6.2015.md
            - 'Seminar 11': cpp/seminar11.2015.md
            - 'Seminar 14': cpp/seminar14.2015.md
    - Results C++:
        - 'Results': 2016.cpp/results.md
        - 'Task 0':
            - 'Baranov': 2016.cpp/task0/baranov.md
            - 'Boldyrev': 2016.cpp/task0/boldyrev.md
            - 'Gusev': 2016.cpp/task0/gusev.md
            - 'Kharisov': 2016.cpp/task0/kharisov.md
            - 'Kostyleva': 2016.cpp/task0/kostyleva.md
            - 'Milyaev': 2016.cpp/task0/milyaev.md
            - 'Turchinovich': 2016.cpp/task0/turchinovich.md
            - 'Zhuk': 2016.cpp/task0/zhuk.md
    - Extras:
        - 'Acceptance': bitbucket.md
        - 'Using namespaces': using-namespaces.md
        - 'CMake': cmake.md
        - 'Svn': using-subversion.md
        - 'GoogleTest': using-googletest.md
        - 'AcceptanceTasks': final-tasks.md

