site_name: OOP Practice Docs
pages:
    - Home: index.md
    - C++:
        - Tasks:
            - 'Task 1': 2017.cpp/task1.md
            - 'Task 2': 2017.cpp/task2.md
            - 'Task 3': 2017.cpp/task3.md
            - 'Task 4': 2017.cpp/task4.md
            - 'Task 5': 2017.cpp/task5.md
        - 'Results':
            - 'Overall': 2017.cpp/results.md
            - 'Battleship': 2017.cpp/battleship_stats.md
            - 'Details':
                - 'Bastrykina': 2017.cpp/results/bastrykina.md
                - 'Chmil': 2017.cpp/results/chmil.md
                - 'Galios': 2017.cpp/results/galios.md
                - 'Grigorovich': 2017.cpp/results/grigorovich.md
                - 'Petin': 2017.cpp/results/petin.md
                - 'Pushkov': 2017.cpp/results/pushkov.md
                - 'Razumov': 2017.cpp/results/razumov.md
                - 'Snegireva': 2017.cpp/results/snegireva.md
                - 'Shustova': 2017.cpp/results/shustova.md
                - 'Voloshina': 2017.cpp/results/voloshina.md
                - 'Yashin': 2017.cpp/results/yashin.md
    - Extras:
        - 'Acceptance': bitbucket.md
        - 'Using namespaces': using-namespaces.md
        - 'CMake': cmake.md
        - 'Svn': using-subversion.md
        - 'GoogleTest': using-googletest.md
        - 'AcceptanceTasks': final-tasks.md
    - Archive:
        - '2017 Java':
            - 'Tasks':
                - 'Task 1': 2017.java/task1.md
                - 'Task 2': 2017.java/task2.md
                - 'Task 3': 2017.java/task3.md
                - 'Task 4': 2017.java/task4.md
            - 'Seminars Java':
                - 'Seminar 2': 2017.java/seminar2.md
                - 'Seminar 3': 2017.java/seminar3.md
        - '2016 C++':
            - 'Seminars C++':
                - 'Seminar 1': 2016.cpp/seminar1.md
                - 'Seminar 3': 2016.cpp/seminar3.md
                - 'Seminar 4': 2016.cpp/seminar4.md
                - 'Seminar 14': 2016.cpp/seminar14.md
        - '2015 C++':
            - 'Seminar 1': cpp/seminar1.2015.md
            - 'Seminar 2': cpp/seminar2.2015.md
            - 'Seminar 3': cpp/seminar3.2015.md
            - 'Seminar 5': cpp/seminar5.2015.md
            - 'Seminar 6': cpp/seminar6.2015.md
            - 'Seminar 11': cpp/seminar11.2015.md
            - 'Seminar 14': cpp/seminar14.2015.md

