site_name: OOP Practice Docs
pages:
    - Home: index.md
    - Seminars C++:
        - 'Seminar 1': seminar1.md
        - 'Seminar 2': seminar2.md
        - 'Seminar 3': seminar3.md
        - 'Seminar 5': seminar5.md
        - 'Seminar 6': seminar6.md
        - 'Seminar 11': seminar11.md
        - 'Seminar 14': seminar14.md
    - Extras:
        - 'Acceptance': bitbucket.md
        - 'Using namespaces': using-namespaces.md
        - 'CMake': cmake.md
        - 'Svn': using-subversion.md
        - 'GoogleTest': using-googletest.md
        - 'AcceptanceTasks': final-tasks.md
